package com.endfield.talosIIarchive.controller.dto

import com.endfield.talosIIarchive.model.Operator

data class OperatorSummaryDTO(
    val id: Long,
    val name: String,
    val rarity: String,
    val imageUrl: String?,
    val element: String,
    val weaponType: String,
    val operatorClass: String
)

data class OperatorDetailDTO(
    val id: Long,
    val name: String,
    val rarity: String,
    val imageUrl: String?,
    val element: String,
    val weaponType: String,
    val operatorClass: String,
    val strength: Int,
    val agility: Int,
    val intellect: Int,
    val will: Int,
    val basicAttack: String,
    val basicAttackDescription: String,
    val battleSkill: String,
    val battleSkillDescription: String,
    val battleSkillSpCost: Int,
    val comboSkill: String,
    val comboSkillDescription: String,
    val comboSkillCooldown: Int,
    val ultimate: String,
    val ultimateDescription: String,
    val ultimateEnergyCost: Int,
    val baseTalent1: String,
    val baseTalent2: String,
    val combatTalent1: String,
    val combatTalent2: String,
    val p1: String?,
    val p1Effect: String?,
    val p2: String?,
    val p2Effect: String?,
    val p3: String?,
    val p3Effect: String?,
    val p4: String?,
    val p4Effect: String?,
    val p5: String?,
    val p5Effect: String?,
    val conceptArt1: String?,
    val conceptArt2: String?,
    val conceptArt3: String?
)

fun Operator.toSummaryDTO() = OperatorSummaryDTO(
    id = this.id,
    name = this.name,
    rarity = "${this.rarity.stars}★",
    imageUrl = this.imageUrl,
    element = this.element.name,
    weaponType = this.weaponType.name,
    operatorClass = this.operatorClass.name
)

fun Operator.toDetailDTO() = OperatorDetailDTO(
    id = this.id,
    name = this.name,
    rarity = "${this.rarity.stars}★",
    imageUrl = this.imageUrl,
    element = this.element.name,
    weaponType = this.weaponType.name,
    operatorClass = this.operatorClass.name,
    strength = this.strength,
    agility = this.agility,
    intellect = this.intellect,
    will = this.will,
    basicAttack = this.basicAttack,
    basicAttackDescription = this.basicAttackDescription,
    battleSkill = this.battleSkill,
    battleSkillDescription = this.battleSkillDescription,
    battleSkillSpCost = this.battleSkillSpCost,
    comboSkill = this.comboSkill,
    comboSkillDescription = this.comboSkillDescription,
    comboSkillCooldown = this.comboSkillCooldown,
    ultimate = this.ultimate,
    ultimateDescription = this.ultimateDescription,
    ultimateEnergyCost = this.ultimateEnergyCost,
    baseTalent1 = this.baseTalent1,
    baseTalent2 = this.baseTalent2,
    combatTalent1 = this.combatTalent1,
    combatTalent2 = this.combatTalent2,
    p1 = this.p1,
    p1Effect = this.p1Effect,
    p2 = this.p2,
    p2Effect = this.p2Effect,
    p3 = this.p3,
    p3Effect = this.p3Effect,
    p4 = this.p4,
    p4Effect = this.p4Effect,
    p5 = this.p5,
    p5Effect = this.p5Effect,
    conceptArt1 = this.conceptArt1,
    conceptArt2 = this.conceptArt2,
    conceptArt3 = this.conceptArt3
)